// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZv8_P25B6JbDiU-LVuja3hQVlq4yZ_0I',
    appId: '1:1076971105388:web:9726c11d6908fd99a4bc49',
    messagingSenderId: '1076971105388',
    projectId: 'productivity-app-b7881',
    authDomain: 'productivity-app-b7881.firebaseapp.com',
    storageBucket: 'productivity-app-b7881.firebasestorage.app',
    measurementId: 'G-P5MQG7VDY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCHg9g8JApB7xbSBmnhX5hWxGBamxLuI',
    appId: '1:1076971105388:android:1d35a47f121571fea4bc49',
    messagingSenderId: '1076971105388',
    projectId: 'productivity-app-b7881',
    storageBucket: 'productivity-app-b7881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3T3GFu4S40VqD-uMs8XcxZHUZ9N85KE',
    appId: '1:1076971105388:ios:bc23c284a2af48e7a4bc49',
    messagingSenderId: '1076971105388',
    projectId: 'productivity-app-b7881',
    storageBucket: 'productivity-app-b7881.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3T3GFu4S40VqD-uMs8XcxZHUZ9N85KE',
    appId: '1:1076971105388:ios:bc23c284a2af48e7a4bc49',
    messagingSenderId: '1076971105388',
    projectId: 'productivity-app-b7881',
    storageBucket: 'productivity-app-b7881.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZv8_P25B6JbDiU-LVuja3hQVlq4yZ_0I',
    appId: '1:1076971105388:web:cb1c691ecf2dc1a7a4bc49',
    messagingSenderId: '1076971105388',
    projectId: 'productivity-app-b7881',
    authDomain: 'productivity-app-b7881.firebaseapp.com',
    storageBucket: 'productivity-app-b7881.firebasestorage.app',
    measurementId: 'G-7N1C58KT0R',
  );
}
